/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import wordgame.model.SecretWord;
import wordgame.model.Game;
import wordgame.view.GameGUI;
import wordgame.controller.GameController;

public class App {

   public static void main(String[] args) {
      SecretWord secret = new SecretWord("chocolate");
      Game game = new Game(secret);
      GameController controller = new GameController(game);
   }
}
